### ISSUE TITLE
`esm` error when trying to execute in browser

### ISSUE THREAD

**Issue by retotrinkler** [Trinkler/imagewallet-tx#20]
Please provide the following information:

This error occurs in both
- imagewallet.io as well as
- agora.trade

### Expected behaviour

Able to import in browser;

### Actual behaviour

See this branch https://github.com/Trinkler/imagewallet.io/tree/iw-tx as an example

```javascript
 WARNING  Compiled with 5 warnings                                                                16:58:41

 warning  in ./node_modules/@trinkler/imagewallet-tx/node_modules/esm/esm.js

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/@trinkler/imagewallet-tx/node_modules/esm/esm.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/lazy-debug-legacy/src/functions.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/lazy-debug-legacy/src/functions.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/@trinkler/imagewallet-tx/node_modules/esm/esm.js
```

### Information about our environment

* OS & Verison
* Browser & Version
* Parity version
* ... other helpful information

**Comment by takahser** [comment]
The source of this error was the imagewallet-tx package. In the newest version, it leverages the esm package, which is, as discussed, not compatible with browser environments.
The solution was to make the imagewallet-tx package multi-environment capable. Basically, it would now [avoid loading esm into apps running on a browser environment](https://github.com/Trinkler/imagewallet-tx/pull/21/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R57). For implementation details please conduct https://github.com/Trinkler/imagewallet-tx/pull/21.
